[workspace]
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
name = "draft-scipy-2025-proceedings-submission"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks.serve]
description = "Start the current project as a website"
cwd = "paper"
cmd = "myst start"

[tasks.build-ci]
description = "Build static HTML site content in automated CI"
cwd = "paper"
cmd = "myst build --html --ci"

[tasks.start]
description = "Build and serve the paper"
depends-on = ["serve"]

[tasks.clean]
description = "Clean the build directories"
cwd = "paper"
cmd = "myst clean"

[dependencies]
mystmd = ">=1.5.1,<2"
typst = ">=0.13.1,<0.14"
