[workspace]
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
name = "draft-scipy-2025-proceedings-submission"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mystmd = ">=1.3.28,<2"
typst = ">=0.13.1,<0.14"
