[workspace]
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
name = "draft-scipy-2025-proceedings-submission"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks.serve]
cwd = "paper"
cmd = "myst start"

[tasks.build-ci]
cwd = "paper"
cmd = "myst build --html --ci"

[tasks.start]
depends-on = ["serve"]

[dependencies]
mystmd = ">=1.3.28,<2"
typst = ">=0.13.1,<0.14"
